In [ ]:
# What is NumPy?
# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, 
# fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. 
# It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.

In [ ]:
# NumPy is a Python library.

# NumPy is used for working with arrays.

# NumPy is short for "Numerical Python".

In [ ]:
# NumPy is a Python library used for working with arrays. 
# It also has functions for working in domain of linear algebra,
# fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant.
# It is an open source project
# and you can use it freely.

In [ ]:
# what is array in python
 Arrays are a fundamental data structure, and an important part of most programming languages. 
In Python, they are containers which are able to store more than one item at the same time. Specifically, 
they are an ordered collection of elements with every value being of the same data type.


In [ ]:
# arrays in numpy

# for install numpy in vs code 
# write in Terminal  
# pip install numpy

In [ ]:
# arrays examples

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [ ]:
ar=np.array([3,5,45,14,78])
ar

In [ ]:
a=np.arrange(6)
a2=a[np.newaxis,:]
a2.shape
(1,6)

In [4]:
import numpy as np
a=np.array([5,5,5,5,5,5])
type(a)
a

array([5, 5, 5, 5, 5, 5])

In [7]:
len(a)

6

In [8]:
a[0]

5

In [9]:
a[0:]

array([5, 5, 5, 5, 5, 5])

In [ ]:
# list of lists( Two Dimensions array).

In [ ]:
# The numpy ndarray class is used to represent both matrices and vertors.

In [12]:
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
len(b)

3

In [11]:
b[0]

array([5, 5, 5])

In [13]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [16]:
import numpy as np
c=np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [17]:
d=np.zeros(2)
d

array([0., 0.])

In [19]:
d=np.ones(3)
d

array([1., 1., 1.])

In [21]:
e=np.empty(3)
e

array([1., 1., 1.])

In [22]:
# with range of elements
f=np.arange(6)
f

array([0, 1, 2, 3, 4, 5])

In [25]:
#with specific range of elements
g=np.arange(2, 20)
g

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [27]:
h=np.arange(2,20, 2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
# linerly spaced arrays
k=np.linspace(0,10,num=5)#  gives use 5 nums
k

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
# specific data types in arrays
l=np.ones(5,dtype=np.int8)
l

array([1, 1, 1, 1, 1], dtype=int8)

In [32]:
m=np.ones(3, dtype=np.float64)
m

array([1., 1., 1.])

# 2-D arrays

In [33]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3-D Array

In [38]:
p=np.arange(24).reshape(2,3,4)
p

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])