# numpy practice session

In [1]:
# for vs code 
# pip install numpy

In [2]:
# import this library in jupyter notebook

In [3]:
import numpy as np

# creating an array using numpy

In [4]:
import numpy as np
food=np.array(["pakora","samoosa","Raita"])
food

array(['pakora', 'samoosa', 'Raita'], dtype='<U7')

# 1-D Array

In [5]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[0]

'pakora'

In [12]:
food[1]

'samoosa'

In [13]:
food[2]

'Raita'

In [14]:
price.mean()

5.0

In [15]:
# Zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# specify 
import numpy as np
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
np.arange(1, 30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
# specify interval
np.arange(2,20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# table of 5
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
# line space
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.linspace(0,10,num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [25]:
np.linspace(1,100,num=20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [26]:
# spacify your data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [27]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [28]:
a=np.array([10,12,15,2,4,6,100,320,34,.5, .9,2.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,  34. ,
         0.5,   0.9,   2.5,  10.3])

In [29]:
b= np.array([10.2,3.4,91.5,45,67.3])
b

array([10.2,  3.4, 91.5, 45. , 67.3])

In [30]:
c=np.concatenate((a,b))
c

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,  34. ,
         0.5,   0.9,   2.5,  10.3,  10.2,   3.4,  91.5,  45. ,  67.3])

In [31]:
c.sort()
c

array([  0.5,   0.9,   2. ,   2.5,   3.4,   4. ,   6. ,  10. ,  10.2,
        10.3,  12. ,  15. ,  34. ,  45. ,  67.3,  91.5, 100. , 320. ])

# 2- D Arrays

In [32]:
x=np.array([[1,2],[3,4,]])
x

array([[1, 2],
       [3, 4]])

In [33]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [34]:
np.concatenate((x,y),axis=0)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
np.concatenate((x,y),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [36]:
a=np.array([[[0,1,2,3],
                     [4,5,6,7]],
                    
                     [[0,1,2,3],
                      [4,5,6,7]],
             
                     [[0,1,2,3],
                      [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [37]:
# To fined the number of dimensions
a.ndim

3

In [38]:
type(a)

numpy.ndarray

In [39]:
b= np.array([[5,6,7],
             [8,9,10],
             [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [40]:
b.ndim

2

In [41]:
a.size

24

In [42]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [43]:
a.shape

(3, 2, 4)

In [44]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
# reshape
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
# reshape

In [47]:
np.reshape(a,newshape=(1,9), order="c")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Convert 1-D into 2-D

In [48]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a.shape

(9,)

In [51]:
b=a[np.newaxis,:] # row wise 2d conversion
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
b.shape

(1, 9)

In [55]:
c=a[: ,np.newaxis]   # column wise 2d conversion
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [60]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
a.sum()

45

In [63]:
a.mean()

5.0

# GO on GOOGLE AND OPEN NUMPY PACKAGE,USER GUIDE,ABSOLUTE BASICSS FOR BEGINERS

In [3]:
import numpy as np
a=np.arange(6)
a2=a[np.newaxis,:]
a2.shape


(1, 6)

In [4]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print (a[0])


[1 2 3 4]


In [6]:
print(a[1])

[5 6 7 8]


In [7]:
print (a[2])

[ 9 10 11 12]


In [8]:
np.zeros(2)


array([0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.empty(2)

array([0., 0.])

In [11]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [12]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [13]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.ones(2,dtype=np.int32)

array([1, 1])

In [16]:
np.ones(2,dtype=np.int64)

array([1, 1], dtype=int64)

# Adding, Removing , Sorting Elements

In [3]:
import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [4]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a= np.array([1, 2, 3, 4])
b= np.array([5, 6, 7, 8])

# concatenate the arrays
    
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
x=np.array([[1, 2],[3, 4]])
y=np.array([[5, 6]])
np.concatenate((x, y),axis=0)



array([[1, 2],
       [3, 4],
       [5, 6]])

# How to shape and size of an array

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])


array_example.ndim  # TO find the number of dimensions of the array



3

In [15]:
array_example.size # find the total number of elements in the array 

24

In [16]:
array_example.shape  # find the shape of your array


(3, 2, 4)

# Can you Reshape an array?

In [4]:
import numpy as np
a= np.arange(6)
print(a)


[0 1 2 3 4 5]


In [5]:
# Reshape an array with three rows and two columns.
b=a.reshape(3,2)
print(b)


[[0 1]
 [2 3]
 [4 5]]


In [6]:
# reshape wirh two rows and three columns.
b=a.reshape(2,3)
print(b)


[[0 1 2]
 [3 4 5]]


In [8]:
# With np. reshape, we can specify a few optional parameters.

np.reshape(a, newshape=(1,6), order='c')


array([[0, 1, 2, 3, 4, 5]])

# IMPORTANT. How to convert a 1D array into a 2D array ( how to add a new axis to an array)

In [ ]:
# we can use np.newaxis, np.expand_dims to increase the dimensions of your existing array.



In [9]:
a= np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [11]:
a2= a[np.newaxis, :]
a2.shape

(1, 6)

In [12]:
row_vector = a[:, np.newaxis]
row_vector.shape


(6, 1)

In [13]:
# we can also use   np.expand_dims  to add an axis at index position 1 with

b= np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [14]:
c= np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing 

In [15]:
data= np.array([1, 2, 3 ])
data[1]

2

In [16]:
data[0:2]

array([1, 2])

In [17]:
data[1:]

array([2, 3])

In [18]:
data[-2: ]

array([2, 3])

In [19]:
data[0:3]

array([1, 2, 3])

# Slicing

In [21]:
a= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
print(a[a < 5])


[1 2 3 4]


In [24]:
five_up = (a >=5)
print(a[five_up])


[ 5  6  7  8  9 10 11 12]


In [4]:
import numpy as np
a= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
divisible_by_2 = a[a%2==0]
print(divisible_by_2)


[ 2  4  6  8 10 12]


In [ ]:
# we can select elements that satisfy two conditions using the & and ooperators

In [5]:
c=a[( a > 2 ) & (a < 11) ]
print(c)

[ 3  4  5  6  7  8  9 10]


In [6]:
five_up = (a > 5) | (a == 5)
print(five_up)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# np.nonzero() to select the elements or indices from an array

In [7]:
a= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b= np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [9]:
list_of_coordinates=list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)


(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [10]:
print(a[b])

[1 2 3 4]


In [11]:
not_there = np.nonzero(a == 42)
print(not_there)


(array([], dtype=int64), array([], dtype=int64))


# How to create an array from existing data

In [12]:
a= np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])

arr1 = a[3:8]
arr1


array([4, 5, 6, 7, 8])

In [ ]:
# we can stack them vertically with  vstack   and horizontally with   hstack 


In [6]:
 a1 = np.array([[1, 1],
               [2, 2]])   

a2 = np.array([[3, 3],
              [4, 4]])

In [7]:
import numpy as np
np.vstack((a1, a2))


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
np.hstack((a1, a2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [15]:
x = np.arange(1, 25)
x



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
x = np.arange(1,25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
# for split
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [20]:
np.hsplit(x,(3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [22]:
a = np. array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# creat an array b1 by slicing array a and modify the first element of b1
b1= a[0,:]
b1

array([1, 2, 3, 4])

In [25]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [26]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
# for complete copy 
b2= a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operation

In [30]:
data=np.array([1, 2])
ones= np.ones(2, dtype=int)
data+ones



array([2, 3])